# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-14 08:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20171114_0813'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='birthday',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='person',
            name='country_code',
            field=models.CharField(default='CN', max_length=2),
        ),
        migrations.AddField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('M', '男'), ('F', '女'), ('U', '未知')], default='U', max_length=10),
        ),
    ]
