# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-15 08:41
from __future__ import unicode_literals

import customs.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_person_nickname'),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('country_code', models.CharField(max_length=2)),
                ('establish', models.DateField(default=django.utils.timezone.now)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('link', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'university',
            },
            bases=(customs.models.UpdateTable, models.Model),
        ),
    ]
