# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-27 03:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_university'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='province',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
