# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-27 06:08
from __future__ import unicode_literals

import customs.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_person_province'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthToken',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('uid', models.CharField(max_length=20, unique=True)),
                ('expired_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'auth_token',
            },
            bases=(customs.models.UpdateTable, models.Model),
        ),
    ]
