# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-27 06:14
from __future__ import unicode_literals

import apps.user.models.token
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_authtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authtoken',
            name='expired_at',
            field=models.DateTimeField(default=apps.user.models.token.expired_time),
        ),
    ]
