# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-15 08:41
from __future__ import unicode_literals

import customs.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('Profession_id', models.PositiveIntegerField()),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('die', models.DateTimeField(default=django.utils.timezone.now)),
                ('goal', models.IntegerField(default=0)),
                ('link', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'product',
            },
            bases=(customs.models.UpdateTable, models.Model),
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('link', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'profession',
            },
            bases=(customs.models.UpdateTable, models.Model),
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('product_id', models.PositiveIntegerField()),
                ('uid', models.PositiveIntegerField()),
                ('profession_id', models.PositiveIntegerField()),
                ('university_id', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'study',
            },
            bases=(customs.models.UpdateTable, models.Model),
        ),
    ]
