# coding:utf8
'''
    认证, 成功, 繁忙错误码(1, -1, 40001~40999)
    描述格式:
        CODE_动作_对象_结果
        CODE_状态_对象
'''
# success and failed
CODE_SUCCESSFUL = 0
CODE_SUCCESSFUL_MSG = 'Successful'

CODE_DEFAULT_BUSY = -1
CODE_DEFAULT_BUSY_MSG = 'Busy'

CODE_FAILED = -2
CODE_FAILED_MSG = 'Failed'


# Token
CODE_BAD_REQUEST = 40001
CODE_BAD_REQUEST_MSG = u'错误的请求'

CODE_UNAUTHORIZED = 40002
CODE_UNAUTHORIZED_MSG = u'无访问权限'

CODE_ADMIN_REQUIRED = 40003
CODE_ADMIN_REQUIRED_MSG = u'管理员权限'

CODE_BAD_CREDENTIAL = 40004
CODE_BAD_CREDENTIAL_MSG = u'无效的凭据'

CODE_BAD_ARGUMENT = 40005
CODE_BAD_ARGUMENT_MSG = u'无效参数'

CODE_BAD_HOSTNAME = 40006
CODE_BAD_HOSTNAME_MSG = u'无效的HOST'

CODE_BAD_TOKEN = 40007
CODE_BAD_TOKEN_MSG = u'无效的token'

CODE_EXPIRED_TOKEN = 40008
CODE_EXPIRED_TOKEN_MSG = u'token已过期'

CODE_UNEXIST_TOKEN = 40009
CODE_UNEXIST_TOKEN_MSG = u'token不存在'


# SYNC
CODE_BAD_ACTION = 40207
CODE_BAD_ACTION_MSG = u'无效动作'

CODE_BAD_SIGN = 40208
CODE_BAD_SIGN_MSG = u'签名验证失败'

CODE_FAILED_SYNC = 40209
CODE_FAILED_SYNC_MSG = u'同步数据失败'


# DB
CODE_EXECUTE_MYSQL_FAILED = 40301
CODE_EXECUTE_MYSQL_FAILED_MSG = '执行sql语句失败'
