"""
工单错误码
"""
# task
CODE_CREATE_TICKET_TASK_FAILED = 44001
CODE_CREATE_TICKET_TASK_FAILED_MSG = u'创建ticket task失败'

CODE_UNEXIST_TICKET_TASK = 44002
CODE_UNEXIST_TICKET_TASK_MSG = u'不存在ticket task'

CODE_NOTALLOW_SCORE_TICKET_TASK = 44003
CODE_NOTALLOW_SCORE_TICKET_TASK_MSG = u'不支持的评分'


# status
CODE_NOTALLOW_CHANGE_TICKET_STATUS = 44101
CODE_NOTALLOW_CHANGE_TICKET_STATUS_MSG = u'该ticket不允许更改'


# Type
CODE_CREATE_TICKET_TYPE_FAILED = 44201
CODE_CREATE_TICKET_TYPE_FAILED_MSG = u'创建ticket type失败'
