"""
工单错误码
"""
# task
CODE_CREATE_TICKET_TASK_FAILED = 44001
CODE_CREATE_TICKET_TASK_FAILED_MSG = u'创建ticket task失败'

CODE_UNEXIST_TICKET_TASK = 44002
CODE_UNEXIST_TICKET_TASK_MSG = u'不存在ticket task'

CODE_NOTALLOW_SCORE_TICKET_TASK = 44003
CODE_NOTALLOW_SCORE_TICKET_TASK_MSG = u'不支持的评分'


# status
CODE_NOTALLOW_CHANGE_TICKET_STATUS = 44101
CODE_NOTALLOW_CHANGE_TICKET_STATUS_MSG = u'该ticket不允许更改'


# Type
CODE_CREATE_TICKET_TYPE_FAILED = 44201
CODE_CREATE_TICKET_TYPE_FAILED_MSG = u'创建ticket type失败'

CODE_UNEXIST_TICKET_TYPE = 44202
CODE_UNEXIST_TICKET_TYPE_MSG = u'ticket type不存在'

CODE_ALREADY_EXISTED_TICKET_TYPE = 44203
CODE_ALREADY_EXISTED_TICKET_TYPE_MSG = u'ticket type已存在'


# Node
CODE_TOO_MANY_TICKET_ROOT_NODE = 44301
CODE_TOO_MANY_TICKET_ROOT_NODE_MSG = u'root节点太多'

CODE_LEAK_TICKET_ROOT_NODE = 44302
CODE_LEAK_TICKET_ROOT_NODE_MSG = u'root节点缺失'

CODE_VALID_FORMAT_TICKET_NODE = 44303
CODE_VALID_FORMAT_TICKET_NODE_MSG = u'非法的ticket node结构'

CODE_CREATE_TICKET_NODE_FAILED = 44304
CODE_CREATE_TICKET_NODE_FAILED_MSG = u'创建ticket node失败'

CODE_UNEXIST_TICKET_NODE = 44310
CODE_UNEXIST_TICKET_NODE_MSG = u'ticket node不存在'
